# Generated by Django 4.2 on 2023-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films_id', models.IntegerField(blank=True, null=True)),
                ('cover', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'covers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id_films', models.AutoField(primary_key=True, serialize=False)),
                ('savedate', models.DateField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('id_dvd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'films',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('global_field', models.TextField(blank=True, db_column='global', null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'globals',
                'managed': True,
            },
        ),
    ]
