# Generated by Django 4.2 on 2023-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
