# Generated by Django 4.2 on 2023-04-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0002_alter_covers_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Globals',
        ),
    ]
