# Generated by Django 4.2 on 2023-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0003_delete_globals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='id_films',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='covers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
