# Generated by Django 4.2 on 2023-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0004_rename_id_films_films_id_remove_films_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
