# Generated by Django 4.2 on 2023-04-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0006_rename_id_dvd_films_dvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covers',
            name='films_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymoviebook.films'),
        ),
    ]
