# Generated by Django 4.2 on 2023-04-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0007_alter_covers_films_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covers',
            old_name='films_id',
            new_name='films',
        ),
    ]
