# Generated by Django 4.2 on 2023-04-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviebook', '0008_rename_films_id_covers_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covers',
            name='id',
        ),
        migrations.AlterField(
            model_name='covers',
            name='films',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mymoviebook.films'),
        ),
    ]
